[versions]
#Gradle
gradle-plugin = "8.8.0"
#Kotlin
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
coroutines = "1.10.1"
serialization = "1.7.3"
datetime = "0.6.1"
#Jetpack
core = "1.15.0"
appcompat = "1.7.0"
recyclerview = "1.4.0"
room = "2.6.1"
fragment = "1.8.5"
navigation = "2.8.6"
splash = "1.0.1"
#Google
material = "1.12.0"
play-services-code-scanner = "16.1.0"
#Koin
koin-bom = "4.0.0"
#Misc
desugar = "2.1.4"
qrgenerator = "1.0.1"
swipereveallayout = "1.4.0"
timber = "5.0.1"
#Testing
junit = "4.13.2"
core-testing = "2.2.0"
robolectric = "4.14.1"
mockk = "1.13.16"
junit-ext = "1.2.1"
espresso = "3.6.1"

[libraries]
#Jetbrains
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
#Jetpack
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
#Google
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "play-services-code-scanner" }
#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android" }
#Misc
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
swipereveallayout = { module = "com.github.hydrated:swipereveallayout", version.ref = "swipereveallayout" }
qrgenerator = { module = "com.github.androidmads:qrgenerator", version.ref = "qrgenerator" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
#Testing
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle-plugin" }
androidLibrary = { id = "com.android.library", version.ref = "gradle-plugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
googleDevtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigationSafeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
